---
- hosts: localhost
  vars:
    namespacens: mynamespacens1
    resource_group: myresourcegroup
    location: centralindia
  tasks:
    - name: Create the namespace
      azure_rm_servicebus:
        resource_group: "{{ resource_group }}"
        name: "{{ namespacens }}"
        location: "{{ location }}"
